### ISSUE TITLE
User Profile Directory should be more versatile

### ISSUE THREAD

**Issue by ghost** [DigitMan27/Ragnarok#11]
The user profile directory should be independent of
- The disk volume that the OS is installed in
- The language of the OS

For solving this issue I found [this](https://social.msdn.microsoft.com/Search/en-US/windows/desktop?query=GetUserProfileDirectoryW) WINAPI function.

This function should and will work, only if some data types change correctly.

That's all I could do for now. I leave this issue to anyone that can solve it.

**Comment by DigitMan27** [comment]
See pr #13

**Comment by DigitMan27** [comment]
@xorz57  i think that this issue has to close what u think?

**Comment by ghost** [comment]
@DigitMan27 Yes.
