### ISSUE TITLE
Delete Files and Folders

### ISSUE THREAD

**Issue by DigitMan27** [DigitMan27/Ragnarok#15]
I will try to implement that with [_wrmdir](https://msdn.microsoft.com/en-us/library/wt8es881.aspx) ,[GetFileAttributesW](https://msdn.microsoft.com/en-us/library/aa364944(VS.85).aspx) for the folders and for files with [_wremove](https://msdn.microsoft.com/en-us/library/2da4hk1d.aspx).

**Comment by ghost** [comment]
@DigitMan27 Sounds like a good idea!

**Comment by DigitMan27** [comment]
@xorz57  I try this now

**Comment by DigitMan27** [comment]
the `_wremove` function works for the files if we add the whole path.
Now i will continue wth the folders and the detection of which of the contents of the user folder is file of which is not.

**Comment by ghost** [comment]
@DigitMan27 ok

**Comment by DigitMan27** [comment]
@xorz57 check branch `feature/Del_Fold_Files`.

**Comment by ghost** [comment]
@DigitMan27 Seems to be working fine! Please open a pull request in order to review the code before this branch gets merged.

**Comment by DigitMan27** [comment]
@xorz57 what about error_handling?

**Comment by ghost** [comment]
@DigitMan27 I guess you can check the return value of the functions you called.

**Comment by DigitMan27** [comment]
@xorz57  just run the program and you ll see what i mean.

**Comment by ghost** [comment]
@DigitMan27 I have to set up a virtual machine first (just in case smth goes wrong) 😆

**Comment by DigitMan27** [comment]
@xorz57 just to know the delete works either there is error_handler or not.

**Comment by DigitMan27** [comment]
SEE pr #17
