### ISSUE TITLE
Running Bragi on VM

### ISSUE THREAD

**Issue by DigitMan27** [DigitMan27/Ragnarok#18]
I was running Bragi in a windows 10 pro in the VM but there was some errors.
- MSVCP140.dll is missing
- VCRUNTIME140.dll is missing
- ucrtbased.dll is missing

 reinstall the program to solve the problem.

**Comment by DigitMan27** [comment]
@xorz57  i found [this](https://msdn.microsoft.com/en-us/library/dd293565.aspx).

**Comment by ghost** [comment]
@DigitMan27 I will find out whats happening tomorrow ;) I guess this happens due to some missing msvc++ redistributable ...

**Comment by DigitMan27** [comment]
@xorz57 yup you guess right
if in the `project properties->C/C++->code generation in runtime lib in debug x64` you put `/MTd` the ucrtbased.dll is not appears any more.
Now for the others one possible solution is to include them inside the direcotry of .exe
But i do not want to solve it in that way.

**Comment by ghost** [comment]
@DigitMan27 Cool !!!! 👍

**Comment by ghost** [comment]
@DigitMan27 Should we close this issue now?

**Comment by DigitMan27** [comment]
@xorz57  nope because the other 2 .dll files still appears as errors when i run the .exe to the vm without any redistributable. I will check with redistributable now.

**Comment by DigitMan27** [comment]
@xorz57  i have installed [this](https://www.microsoft.com/en-us/download/details.aspx?id=48145) to the VM but nothing the two dll still throws up as an error + the third one becuase i reset to deafult the runtime lib x64 from `/MTd to /MDd`.

**Comment by DigitMan27** [comment]
@xorz57 check [this](https://stackoverflow.com/questions/28313473/how-can-i-run-a-exe-file-on-any-windows-computer) too.What do you think?

**Comment by ghost** [comment]
@DigitMan27 I am not sure but it looks like static linking might be the solution to this problem.

**Comment by DigitMan27** [comment]
@xorz57  I can not find any solution to this problem. 😢 😞

**Comment by ghost** [comment]
@DigitMan27 Dou you know which system calls cause this to happen?
If yes, then maybe we can replace those with some other system calls.

**Comment by ghost** [comment]
@DigitMan27 Can you make a branch called `safe-testing` that safely deletes files of none importance in the current working directory (For simplicity's sake)? I would like to try out Bragi on my everyday OS.

**Comment by DigitMan27** [comment]
@xorz57 in your every day os it will be no problem because the msvcp140.dll and vcruntime.dll exists
irrelevant but i found [this](https://stackoverflow.com/questions/39094220/c-applicationdebug-version-contains-vs-runtime-libraries-msvcr90-dll-and-msv).

**Comment by DigitMan27** [comment]
plus thsi .dll files is becuase we use VS ''default libs''.
I dont know how exactly say that.

**Comment by DigitMan27** [comment]
@xorz57  The branch `feature/safe_testing` was built.

**Comment by ghost** [comment]
@DigitMan27 

> in your everyday os it will be no problem because the msvcp140.dll and vcruntime.dll exists
irrelevant but I found this.

I see what you mean now ...

**Comment by DigitMan27** [comment]
@xorz57 i run just now the ragnarok.exe having the msvcp140.dll and vcruntime140.dll in the same path and it works.

**Comment by DigitMan27** [comment]
I m a fucking IDIOT!!!!!!!!!!!!!!!!!!!
