### ISSUE TITLE
Add support for unicode paths

### ISSUE THREAD

**Issue by ghost** [DigitMan27/Ragnarok#9]
For example, paths using the Greek alphabet should be supported too.
`std::string` does not support Unicode characters, thus `std::wstring` should be used instead.

**Comment by DigitMan27** [comment]
`std::wstring` only? or both `std::string` , `std::wstring`.

**Comment by ghost** [comment]
@DigitMan27 GetUserName is causing some trouble with the data types but I think we can work it out. Hopefully, after we resolve the data types only `std::wstring` will be needed.

**Comment by DigitMan27** [comment]
@xorz57  The unicode encoding it will be the `UTF-8` or another (for example `UTF-16,UTF-32`) ?
I suggest the `UTF-8` because encodes all characters into 8 bits (like ASCII) so if there is any latin character in a sub folder or a file there will be no problem on encoding-decoding it.

**Comment by ghost** [comment]
@DigitMan27 

From [this](https://en.wikipedia.org/wiki/Comparison_of_Unicode_encodings) wikipedia article.

> A UTF-8 file that contains only ASCII characters is identical to an ASCII file. Legacy programs can generally handle UTF-8 encoded files, even if they contain non-ASCII characters. For instance, the C printf function can print a UTF-8 string, as it only looks for the ASCII '%' character to define a formatting string, and prints all other bytes unchanged, thus non-ASCII characters will be output unchanged.

> UTF-16 and UTF-32 are incompatible with ASCII files, and thus require Unicode-aware programs to display, print and manipulate them, even if the file is known to contain only characters in the ASCII subset. Because they contain many zero bytes, the strings cannot be manipulated by normal null-terminated string handling for even simple operations such as copy.

About what you said:

> I suggest the UTF-8 because encodes all characters into 8 bits (like ASCII) so if there is any Latin character in a subfolder or a file there will be no problem on encoding-decoding it.

The problem is not latin characters but non-latin characters. That's what I am concerned about. I am not yet sure which encoding is best. The one that supports most languages would be fine, as long as it does not introduce problems.

[Here](http://www.cplusplus.com/reference/string/wstring/) is some documentation about `std::wstring`.

**Comment by ghost** [comment]
@DigitMan27 I think I fixed this. Take a look.

**Comment by ghost** [comment]
@DigitMan27 Here are all [windows data types](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx)

**Comment by DigitMan27** [comment]
@xorz57 do not delete the branch `feature/unicode-support`

**Comment by ghost** [comment]
@DigitMan27 So you want us to continue work on this branch until issue #11 is resolved?

**Comment by DigitMan27** [comment]
@xorz57  I suggest to work first the issue #11 in that branch and after that to continue with issue #9 (current issue).
NOTE: if that is not possible then make a copy of that branch and work there.
